Update `DataProcessing` and add instructions/code to allow compatibility with new GO releases
benfulcher/GeneCategoryEnrichmentAnalysis pull request #3
Opened 2022-04-16 04:34 UTC by alyssadai

Addresses #2 .

- Adds new directory `oboConversion/` which includes instructions and code for converting `go-basic.obo` files for more recent GO releases into sqlite databases.
- Changes MySQL code in `DataProcessing/` scripts to sqlite commands.
- Updates repo README to mention deprecation of MySQL dumps of GO and the current workaround.

2022-04-16 23:57 UTC, gdevenyi requested changes

2022-04-16 23:57 UTC, gdevenyi commented on DataProcessing/GetGOTerms.m
> +dbc = sqlite('D:\McGill\cobralab\PS_Dimensions\gene_mapping\GCEA_data\2022-01-13\GO_2022-01-13.db', 'readonly');
Don't add absolute hard coded paths, use a generic relative path for someone using this in a project.

2022-04-16 23:57 UTC, gdevenyi commented on DataProcessing/ReadDirectAnnotationFile.m
> +    % https://github.com/benfulcher/GCEA_FalsePositives is needed to run
Why not just fix the original link?

2022-04-16 23:57 UTC, gdevenyi commented on DataProcessing/propagateHierarchy.m
> +dbc = sqlite('D:\McGill\cobralab\PS_Dimensions\gene_mapping\GCEA_data\2022-01-13\GO_2022-01-13.db', 'readonly');
Don't hardcode specific paths.

2022-06-08 04:36 UTC, benfulcher approved these changes

2022-06-08 04:36 UTC, merged